# sidekiq -C config/sidekiq_config.yml

# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:pidfile: ./tmp/pids/sidekiq.pid
:verbose: false
:concurrency:  10
# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - default
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30

# you can override concurrency based on environment
production:
  :concurrency: 25
staging:
  :concurrency: 15